<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="solvds-MacBook-Pro.local" failures="2" tests="2" name="Command line test" time="0.029" errors="0" timestamp="2024-07-02T16:51:20 ART">
  <testcase classname="com.solvd.advancedautomation.base.login.LoginTest" name="test1" time="0.004">
    <failure type="java.lang.AssertionError" message="Failing test1 on purpose">
      <![CDATA[java.lang.AssertionError: Failing test1 on purpose
at com.solvd.advancedautomation.base.login.LoginTest.test1(LoginTest.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.solvd.advancedautomation.base.login.LoginTest" name="test2" time="0.0">
    <failure type="java.lang.AssertionError" message="Failing test2 on purpose">
      <![CDATA[java.lang.AssertionError: Failing test2 on purpose
at com.solvd.advancedautomation.base.login.LoginTest.test2(LoginTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Command line test -->
